# Generated by Django 4.1.2 on 2022-11-09 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_uploadfiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='log',
        ),
        migrations.AddField(
            model_name='job',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='JobsLogos'),
        ),
    ]
