# Generated by Django 4.1.2 on 2022-11-09 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_job_log_job_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='logo',
            field=models.FileField(upload_to='JobsLogos'),
        ),
    ]
